name = "nubes"

# [[functions]]
# lambda = "Gateway"
# task = "gateway"


# [[functions]]
# lambda = "SetField"
# task = "set-hotel-rate"

# [[functions]]
# lambda = "CityGetHotelsCloseTo"
# task = "recommend-location"

# [[functions]]
# lambda = "CityGetHotelsWithBestRates"
# task = "recommend-price"


# [[functions]]
# lambda = "Delete"
# task = "delete-user"

# [[functions]]
# lambda = "UserVerifyPassword"
# task = "login"

# ---

[[functions]]
lambda = "Export"
task = "reserve"

[[functions]]
lambda = "ReferenceGetStubs"
task = "get-user-reservations"

# ---

# [[functions]]
# lambda = "Export"
# task = "user-registration"

# [[functions]]
# lambda = "ReferenceGetStubs"
# task = "get-hotels"
