frameworkVersion: '>3.24.0'

service: faas
provider:
  name: aws
  runtime: go1.x
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  # Default timeout for functions (default: 6 seconds)
  # Note: API Gateway has a maximum timeout of 30 seconds
  #timeout: 60
  # Use function versioning (enabled by default)
  versionFunctions: false
  # By default, one IAM Role is shared by all the Lambda functions in your service
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "*"

package:
  individually: true
  exclude:
    - "bin/*"
    - "**/**"

functions:
  Load:
    name: Load
    handler: bin/Load
    package:
      include:
        - bin/Load
    maximumRetryAttempts: 0
    maximumEventAge: 60
  Export:
    name: Export
    handler: bin/Export
    package:
      include:
        - bin/Export
    maximumRetryAttempts: 0
    maximumEventAge: 60
  Delete:
    name: Delete
    handler: bin/Delete
    package:
      include:
        - bin/Delete
    maximumRetryAttempts: 0
    maximumEventAge: 60
  GetField:
    name: GetField
    handler: bin/GetField
    package:
      include:
        - bin/GetField
    maximumRetryAttempts: 0
    maximumEventAge: 60
  SetField:
    name: SetField
    handler: bin/SetField
    package:
      include:
        - bin/SetField
    maximumRetryAttempts: 0
    maximumEventAge: 60
  ReferenceGetSortKeysByPartitionKey:
    name: ReferenceGetSortKeysByPartitionKey
    handler: bin/ReferenceGetSortKeysByPartitionKey
    package:
      include:
        - bin/ReferenceGetSortKeysByPartitionKey
    maximumRetryAttempts: 0
    maximumEventAge: 60
  ReferenceGetByIndex:
    name: ReferenceGetByIndex
    handler: bin/ReferenceGetByIndex
    package:
      include:
        - bin/ReferenceGetByIndex
    maximumRetryAttempts: 0
    maximumEventAge: 60

  ProductDecreaseAvailabilityBy:
    name:  ProductDecreaseAvailabilityBy
    handler: bin/ProductDecreaseAvailabilityBy
    package:
      include:
        - bin/ProductDecreaseAvailabilityBy
    maximumRetryAttempts: 0
    maximumEventAge: 60

  UserVerifyPassword:
    name:  UserVerifyPassword
    handler: bin/UserVerifyPassword
    package:
      include:
        - bin/UserVerifyPassword
    maximumRetryAttempts: 0
    maximumEventAge: 60


  NewOrder:
    name:  NewOrder
    handler: bin/NewOrder
    package:
      include:
        - bin/NewOrder
    maximumRetryAttempts: 0
    maximumEventAge: 60
