frameworkVersion: '>3.24.0'

service: faas
provider:
  name: aws
  ecr:
    images:
      faasimage:
        path: ./
  runtime: go1.x
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  # Default timeout for functions (default: 6 seconds)
  # Note: API Gateway has a maximum timeout of 30 seconds
  #timeout: 60
  # Use function versioning (enabled by default)
  versionFunctions: false
  # By default, one IAM Role is shared by all the Lambda functions in your service
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "*"

package:
  individually: false

functions:
  GetField:
    name: GetField
    image:
      name: faasimage	
      command:
        -  GetField
      entryPoint:
        - '/lambda-entrypoint.sh'
    maximumRetryAttempts: 0
    maximumEventAge: 60
  SetField:
    name: SetField
    image:
      name: faasimage	
      command:
        -  SetField
      entryPoint:
        - '/lambda-entrypoint.sh'
    maximumRetryAttempts: 0
    maximumEventAge: 60

  ProductDecreaseAvailabilityBy:
    name:  ProductDecreaseAvailabilityBy
    image:
      name: faasimage	
      command:
        - ProductDecreaseAvailabilityBy
    maximumRetryAttempts: 0
    maximumEventAge: 60

  UserVerifyPassword:
    name:  UserVerifyPassword
    image:
      name: faasimage	
      command:
        - UserVerifyPassword
    maximumRetryAttempts: 0
    maximumEventAge: 60
