frameworkVersion: '>3.24.0'

service: hotel-baseline-simple
provider:
  name: aws
  runtime: go1.x
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  # Default timeout for functions (default: 6 seconds)
  # Note: API Gateway has a maximum timeout of 30 seconds
  #timeout: 60
  # Use function versioning (enabled by default)
  versionFunctions: false
  # By default, one IAM Role is shared by all the Lambda functions in your service
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:*"
        - "dynamodb:*"
      Resource:
        - "*"

package:
  individually: true
  exclude:
    - "bin/*"
    - "**/**"


functions:
  getHotelsInCitySimple:
    name:  getHotelsInCitySimple
    handler: bin/getHotelsInCity
    package:
      include:
        - bin/getHotelsInCity
    maximumRetryAttempts: 0
    maximumEventAge: 60
  recommendHotelsLocationSimple:
    name:  recommendHotelsLocationSimple
    handler: bin/recommendHotelsLocation
    package:
      include:
        - bin/recommendHotelsLocation
    maximumRetryAttempts: 0
    maximumEventAge: 60
  recommendHotelsRateSimple:
    name:  recommendHotelsRateSimple
    handler: bin/recommendHotelsRate
    package:
      include:
        - bin/recommendHotelsRate
    maximumRetryAttempts: 0
    maximumEventAge: 60
  gatewayBaselineSimple:
    name:  gatewayBaselineSimple
    handler: bin/gateway
    package:
      include:
        - bin/gateway
    maximumRetryAttempts: 0
    maximumEventAge: 60